# Generated by Django 5.0.2 on 2024-02-15 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('rooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('size', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'House',
                'verbose_name_plural': 'Houses',
                'db_table': 'house',
            },
        ),
        migrations.CreateModel(
            name='HouseImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='house', verbose_name='image')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='House.house')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'db_table': 'image',
            },
        ),
    ]
